### PR TITLE
Fix Windows name server loading

### PR DESCRIPTION
**Pull request by erakis**
Fix Windows bad regedit path
Fix Windows bad way to read two consecutive keys in case the first one is empty

### CODE REVIEW

**Comment by davidgfnet** [comment]
Have you actually tested this?
WTF is ret--; ??
I will set up Travis I think :D

**Comment by erakis** [comment]
ret-- was here originally before you did the upgrade to c++. I could have been fix it using YOUR code but I discover your repository later... sorry. It's up to you to fix it or I could make thing more clean in a next commit. Because I have a new commit to push today to fix compiling error on Windows.

**Comment by erakis** [comment]
Let me fix those error I and will come back with something tested on Windows and Linux. 

I didn't know that the code has changed so much. Sorry :(

**Comment by erakis** [comment]
Hi David,

I'm still working on fixing Windows compiling issue..., this take me more time because of major changes compared to the original [(tadns)](https://sourceforge.net/projects/adns/files/tadns/) C library. But ultimately I prefer yours ! :)

Now I successfully compiled it for Windows and Linux, On Linux this work like a charm. But on Windows I'm getting a crash on 
```
~Query() {
	// Remove the entry from the parent deps list
	assert(!deps_on || deps_on->deps.count(this));
	if (deps_on)
		deps_on->deps.erase(this);

	for (auto e: deps)    
		delete e;  //////////////////// <--------- Cause

        // When we leave the stack we get a crash.
}
```
The error is `map/set iterator not incrementablemap/set iterator not incrementable`
But replacing it by
```
for (auto e = deps.begin(); e != deps.end(); )
	deps.erase(e++);
```
fix the issue :)

Another issue on Windows ; The option `DNS_OPT_RECURSIVE_SOLVE` does not work. I'm getting positive value on `select` and then I call `poll` but nothing is received in the `recvfrom` call finally resulting a timeout after 10 seconds. Using Wireshark I see the query and also the response but clearly the `recvfrom` does not get it ! On Linux I tried it but it seems to work all the time and resolving in a short time (< 1sec). Grrr.... I'm working on it.

When reconnecting my code to your library there something I don't understand. When we create a resolver as ` createResolver(0, atimeouts)`. What's the meaning of the atimeouts ? Is it the time living of the query in the cache (kind of ttl DNS by-pass) ? Or a sending (ongoing) timeout ? A clearer name would be appreciate here.

Another question, is it possible to received a AAAA (Ipv6) response from server ? I don't see the case in the callback but the defines are here.

Best regards,

**Comment by davidgfnet** [comment]
Hey!
To be fair I didn't consider Windows at all, so maybe there's some stuff
that won't work on Windows. I will look into it.
The crash you describe sounds scary, I was getting those but I thought I
had fixed them. They might come from race conditions, which would explain
why you get them in one platform. No idea right now, I swapped all the
source out off my brain :D
Thanks for your help!
David

**Comment by erakis** [comment]
The error I'm getting using the recursive mode is [WSAECONNRESET](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx) when calling recvfrom on both socket. By experience and also because I see the response in Wireshark I believe that it is related to a problem of memory or a race condition. But as I'm running Linux on a virtual machine (VMWare) the former create me a couple of interface and a couple of DNS entries. 

1. Good entry
2. VM bad entry
3. VM bad entry

We are inserting the DNS list in ascending order in `getdnsip()`. Once we call `resolve_dns` we also do call getNextServer() that rotate the list use a VM bad entry. I did not found no good way to filter those entries : ( I set a FIXME noticed in the code for that.

Also, I thought I had fixed the `~Query()` crash, but no ! 
```
for (auto e = deps.begin(); e != deps.end();) {
    delete *e;
    e = deps.erase(e);
}
```
Once `erase` is called I'm now getting an out of range iterator assertion... This destructor get called after calling `delete q` in parse_udp : 
```
// Remove the query from the deps list
    delete q;
```

I'm also getting another assertion crash here : 
```
if ((centry = find_cached_query(qtype, name)) != NULL) {
    assert(dep == NULL);
    return;
}
```
while doing a recursive resolve. Not the first time, but the second time it crash. But I'm not sure to understand the idea behind this assert... Hope you can help me ? I defined -DNDEBUG to get the assert crash on Linux but at my surprise this work.

**Pull request closed without merging**
